### ISSUE TITLE
Requesting for brief help file

### ISSUE THREAD

**Issue by reza1372gh** [midas-network/covid19-scenario-modeling-hub_archive#208]
Hi,
I am new to this community and the documentation and the project tree have confused me. 
I want to recreate some of the scenarios and develop a new scenario based on them. How should I start? Could you please provide me with a minimalistic example file? 

Thank you very much for your time and answer.

**Comment by harryhoch** [comment]
The README.md file details the gold standard data to be used, the format of the submission files, and the assumptions for the various scenarios.  To participate in the scenario modeling hub, you should use those gold standard data to define and calibrate a model that will project counts of cases, hospitalizations, and deaths under each of the proposed scenarios.  

If you have more specific questions, please follow-up or contact me directly...
