### ISSUE TITLE
change the y-axis limit when upper confidence limits drive the bounds up.

### ISSUE THREAD

**Issue by nickreich** [midas-network/covid19-scenario-modeling-hub_archive#59]
E.g. in the below image, it would be useful to have the default load of the figures have an upper y-axis limit of 2,500 or so, which would allow for more clear visibility of the different models. 
![image](https://user-images.githubusercontent.com/1280767/118172402-51c51b00-b3fa-11eb-93d4-1fdca1447870.png)

**Comment by nickreich** [comment]
The rule that we use at the forecast hub is that the maximum of the y-axis is
`max(25, 1.2*<maximum value in data>)`
where `data` is any point forecast or any data point, but does not include quantiles other than the median. We include the 25 because there were instances where the data and forecasts are all 0, and that also looked weird.

**Comment by LucieContamin** [comment]
Thank you very much for the suggestion, it has been implemented in the last version of the website.
